# Generated by Django 4.2.11 on 2025-03-05 10:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dasapp', '0005_labworker_medicine_test_alter_customuser_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='labworker',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pharmacist',
            options={},
        ),
        migrations.AlterModelManagers(
            name='labworker',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='pharmacist',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='labworker',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='labworker',
            name='email',
        ),
        migrations.RemoveField(
            model_name='labworker',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='labworker',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='labworker',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='labworker',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='labworker',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='labworker',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='labworker',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='labworker',
            name='password',
        ),
        migrations.RemoveField(
            model_name='labworker',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='labworker',
            name='username',
        ),
        migrations.RemoveField(
            model_name='patientreport',
            name='patient_name',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='password',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='pharmacist',
            name='username',
        ),
        migrations.AddField(
            model_name='labworker',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dasapp.patientreg'),
        ),
        migrations.AddField(
            model_name='pharmacist',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='test',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('4', 'pharmacist'), (2, 'doc'), (1, 'admin'), ('3', 'lab_worker')], default=1, max_length=50),
        ),
    ]
