# Generated by Django 4.2.11 on 2025-03-06 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0006_alter_labworker_options_alter_pharmacist_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreport',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'doc'), ('4', 'pharmacist'), (1, 'admin'), ('3', 'lab_worker')], default=1, max_length=50),
        ),
    ]
