# Generated by Django 4.2.11 on 2025-03-24 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0008_prescription_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientreport',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dasapp.doctorreg'),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='doctor_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientreport',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), ('3', 'lab_worker'), ('4', 'pharmacist'), (2, 'doc')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='patientreport',
            name='lab_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dasapp.labworker'),
        ),
        migrations.AlterField(
            model_name='patientreport',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dasapp.patientreg'),
        ),
        migrations.AlterField(
            model_name='patientreport',
            name='report_data',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patientreport',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='requested', max_length=20),
        ),
    ]
