# Generated by Django 4.2.11 on 2025-03-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0009_patientreport_doctor_patientreport_doctor_notes_and_more'),
    ]

    operations = [
    ]
