# Generated by Django 4.2.11 on 2025-03-24 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0010_auto_20250324_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'doc'), ('3', 'lab_worker'), ('4', 'pharmacist'), (1, 'admin')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='patientreport',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dasapp.doctorreg'),
        ),
    ]
