# Generated by Django 4.2.11 on 2025-03-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0011_alter_customuser_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientreport',
            name='doctor',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'doc'), (1, 'admin'), ('4', 'pharmacist'), ('3', 'lab_worker')], default=1, max_length=50),
        ),
    ]
