# Generated by Django 4.2.11 on 2025-03-24 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0012_remove_patientreport_doctor_and_more'),
    ]

    operations = [
    ]
