# Generated by Django 4.2.11 on 2025-03-24 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0013_auto_20250324_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(2, 'doc'), ('3', 'lab_worker'), (1, 'admin'), ('4', 'pharmacist')], default=1, max_length=50),
        ),
    ]
