# Generated by Django 4.2.11 on 2025-03-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0014_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), ('3', 'lab_worker'), (2, 'doc'), ('4', 'pharmacist')], default=1, max_length=50),
        ),
    ]
