# Generated by Django 4.2.11 on 2025-03-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dasapp', '0015_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[(1, 'admin'), ('4', 'pharmacist'), ('3', 'lab_worker'), (2, 'doc')], default=1, max_length=50),
        ),
    ]
